cc_binary(
	name = "gfwl",
	deps = [],
	srcs = [],
	data = [],
	additional_linker_inputs = [],
	args = [""],
	copts = [""],
	defines = [""],
	env = {"": ""},
	includes = [""],
	linkopts = [""],
	linkshared = False,
	linkstatic = False,
	local_defines = [""],
	malloc = "",
	nocopts = "",
	output_licenses = [""],
	stamp = False,
	tags = [""],
	toolchains = [],
	visibility = [""],
	win_def_file = "",
)
